/*******************************************************************************
* File Name: cycfg_capsense.c
*
* Description:
* CAPSENSE Middleware configuration
* This file should not be modified. It was automatically generated by
* CAPSENSE Configurator 5.0.0.2684
*
********************************************************************************
* Copyright 2023, Cypress Semiconductor Corporation (an Infineon company) 
* or an affiliate of Cypress Semiconductor Corporation.
* SPDX-License-Identifier: Apache-2.0
*
* Licensed under the Apache License, Version 2.0 (the "License");
* you may not use this file except in compliance with the License.
* You may obtain a copy of the License at
*
*     http://www.apache.org/licenses/LICENSE-2.0
*
* Unless required by applicable law or agreed to in writing, software
* distributed under the License is distributed on an "AS IS" BASIS,
* WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
* See the License for the specific language governing permissions and
* limitations under the License.
*******************************************************************************/

#include "cycfg_capsense.h"

/* This enables code only when the CAPSENSE(TM) Middleware is present in the project 
 * or the information about the Middleware presence cannot be obtained.
 */
#if (defined(COMPONENT_MW_CAPSENSE) || !defined(COMPONENT_MW_CORE_MAKE))

#if !defined(CY_DISABLE_CAPSENSE)

#if (CY_CAPSENSE_CORE == __CORTEX_M)

#ifndef CSD_CMODPADS_PORT
#define CSD_CMODPADS_PORT 0xFF
#endif
#ifndef CSD_CMODPADS_PIN
#define CSD_CMODPADS_PIN 0xFF
#endif
#ifndef CSD_CSH_TANKPADS_PORT
#define CSD_CSH_TANKPADS_PORT 0xFF
#endif
#ifndef CSD_CSH_TANKPADS_PIN
#define CSD_CSH_TANKPADS_PIN 0xFF
#endif
#ifndef CSD_CSHIELDPADS_PORT
#define CSD_CSHIELDPADS_PORT 0xFF
#endif
#ifndef CSD_CSHIELDPADS_PIN
#define CSD_CSHIELDPADS_PIN 0xFF
#endif
#ifndef CSD_VREF_EXT_PORT
#define CSD_VREF_EXT_PORT 0xFF
#endif
#ifndef CSD_VREF_EXT_PIN
#define CSD_VREF_EXT_PIN 0xFF
#endif

static cy_stc_capsense_internal_context_t cy_capsense_internalContext;

#if (CY_CAPSENSE_MW_VERSION >= 400)
    static cy_stc_capsense_active_scan_sns_t cy_capsense_activeScanSns[CY_MSC_ENABLED_CH_NUMBER];
#else
    static cy_stc_active_scan_sns_t cy_capsense_activeScanSns[CY_MSC_ENABLED_CH_NUMBER];
#endif

static cy_stc_msc_base_config_t cy_capsense_baseFrame[CY_CAPSENSE_TOTAL_CH_NUMBER];

#if (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0)
    static uint32_t cy_capsense_sensorFrameContext[CY_CAPSENSE_SENSOR_FRAME_SIZE * CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER];
#endif

#if (CY_CAPSENSE_DEBOUNCE_SIZE > 0)
    static uint8_t cy_capsense_debounce[CY_CAPSENSE_DEBOUNCE_SIZE] = {0};
#endif

#if (CY_CAPSENSE_NOISE_ENVELOPE_SIZE > 0)
    static cy_stc_capsense_smartsense_csd_noise_envelope_t cy_capsense_noiseEnvelope[CY_CAPSENSE_NOISE_ENVELOPE_SIZE];
#endif

#if (CY_CAPSENSE_RAW_HISTORY_SIZE > 0)
    static uint16_t cy_capsense_rawFilterHistory[CY_CAPSENSE_RAW_HISTORY_SIZE] = {0};
#endif

#if (CY_CAPSENSE_IIR_HISTORY_LOW_SIZE > 0)
    static uint8_t cy_capsense_iirHistoryLow[CY_CAPSENSE_IIR_HISTORY_LOW_SIZE] = {0};
#endif

#if (CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE > 0)
    static cy_stc_capsense_position_t cy_capsense_positionFilterHistory[CY_CAPSENSE_POSITION_FILTER_HISTORY_SIZE];
#endif

#if (CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE > 0)
    static cy_stc_capsense_touch_t cy_capsense_touchFilterHistory[CY_CAPSENSE_TOUCH_FILTER_HISTORY_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_DIPLEX_SIZE > 0)
    static const uint8_t cy_capsense_diplexTable[CY_CAPSENSE_DIPLEX_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE > 0)
    static uint16_t cy_capsense_csdTouchBuffer[CY_CAPSENSE_CSD_TOUCHPAD_MAX_SENSORS_SIZE] = {0};
#endif

#if (CY_CAPSENSE_CSX_TOUCH_BUFFER_ENABLE > 0)
    static cy_stc_capsense_csx_touch_buffer_t cy_capsense_csxTouchBuffer;
#endif

#if (CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE > 0)
    static cy_stc_capsense_csx_touch_history_t cy_capsense_csxTouchHistory[CY_CAPSENSE_CSX_TOUCH_HISTORY_SIZE] =
    {
    };
#endif

#if (CY_CAPSENSE_BALLISTIC_WIDGET_COUNT > 0)
    static cy_stc_capsense_ballistic_context_t cy_capsense_ballisticContext[CY_CAPSENSE_BALLISTIC_WIDGET_COUNT];
#endif

#if (CY_CAPSENSE_GESTURE_WIDGET_COUNT > 0)
    static cy_stc_capsense_gesture_context_t cy_capsense_gestureContext[CY_CAPSENSE_GESTURE_WIDGET_COUNT];
#endif

#if (CY_CAPSENSE_BIST_EN != 0)
    static uint16_t cy_capsense_bslnInv[CY_CAPSENSE_SENSOR_COUNT];
    static uint32_t cy_capsense_eltdCap[CY_CAPSENSE_ELTD_COUNT];
    static uint32_t cy_capsense_snsCap[CY_CAPSENSE_SENSOR_COUNT];
    static uint32_t cy_capsense_shieldCap[CY_CAPSENSE_TOTAL_CH_NUMBER];
    static uint16_t cy_capsense_wdgtCrc[CY_CAPSENSE_WIDGET_COUNT];
#endif

#if (CY_CAPSENSE_MW_VERSION >= 400)
static cy_stc_capsense_channel_config_t cy_capsense_msc_ch_config[CY_MSC_ENABLED_CH_NUMBER] =
#else
static cy_stc_msc_channel_config_t cy_capsense_msc_ch_config[CY_MSC_ENABLED_CH_NUMBER] =
#endif
{
    {   /* MSC channel 0 */
#if (CY_CAPSENSE_MW_VERSION >= 400)
            .ptrHwBase = CY_MSC0_HW,
            .ptrHwContext = &cy_msc_0_context,
#else
            .ptrMscBase = CY_MSC0_HW,
            .ptrMscContext = &cy_msc_0_context,
#endif
        .portCmod1 = CY_MSC0_Cmod1_PORT,
        .pinCmod1 = CY_MSC0_Cmod1_PIN,
        .portCmod2 = CY_MSC0_Cmod2_PORT,
        .pinCmod2 = CY_MSC0_Cmod2_PIN,
        .dmaWrChIndex = 0u,
        .dmaChainWrChIndex = 0u,
        .dmaRdChIndex = 0u,
        .dmaChainRdChIndex = 0u,
    },
    {   /* MSC channel 1 */
#if (CY_CAPSENSE_MW_VERSION >= 400)
            .ptrHwBase = CY_MSC1_HW,
            .ptrHwContext = &cy_msc_1_context,
#else
            .ptrMscBase = CY_MSC1_HW,
            .ptrMscContext = &cy_msc_1_context,
#endif
        .portCmod1 = CY_MSC1_Cmod1_PORT,
        .pinCmod1 = CY_MSC1_Cmod1_PIN,
        .portCmod2 = CY_MSC1_Cmod2_PORT,
        .pinCmod2 = CY_MSC1_Cmod2_PIN,
        .dmaWrChIndex = 0u,
        .dmaChainWrChIndex = 0u,
        .dmaRdChIndex = 0u,
        .dmaChainRdChIndex = 0u,
    },
};

static cy_stc_capsense_scan_slot_t cy_capsense_scanSlotsConfig[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] =
{
    /* Channel MSC0 */
    {   /* Slot 0 */
        CY_CAPSENSE_BUTTON0_WDGT_ID,
        CY_CAPSENSE_BUTTON0_SNS0_ID
    },
    {   /* Slot 1 */
        0xFFFFu,
        0xFFFFu
    },
    {   /* Slot 2 */
        CY_CAPSENSE_BUTTON2_WDGT_ID,
        CY_CAPSENSE_BUTTON2_SNS0_ID
    },
    {   /* Slot 3 */
        0xFFFFu,
        0xFFFFu
    },
    /* Channel MSC1 */
    {   /* Slot 0 */
        0xFFFFu,
        0xFFFFu
    },
    {   /* Slot 1 */
        CY_CAPSENSE_BUTTON1_WDGT_ID,
        CY_CAPSENSE_BUTTON1_SNS0_ID
    },
    {   /* Slot 2 */
        0xFFFFu,
        0xFFFFu
    },
    {   /* Slot 3 */
        CY_CAPSENSE_BUTTON3_WDGT_ID,
        CY_CAPSENSE_BUTTON3_SNS0_ID
    },
};

#if ((CY_CAPSENSE_DMA_CONFIGURED != 0) && (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0))
static const uint32_t *ptrDmaWrChSnsConfigs[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] = {
    &cy_capsense_sensorFrameContext[0u],
    &cy_capsense_sensorFrameContext[6u],
    &cy_capsense_sensorFrameContext[12u],
    &cy_capsense_sensorFrameContext[18u],
    &cy_capsense_sensorFrameContext[24u],
    &cy_capsense_sensorFrameContext[30u],
    &cy_capsense_sensorFrameContext[36u],
    &cy_capsense_sensorFrameContext[42u],
};

static uint16_t emptySlotValue = 0u;
static const uint16_t *ptrDmaRdChSnsConfigs[CY_CAPSENSE_SLOT_COUNT * CY_CAPSENSE_TOTAL_CH_NUMBER] = {
    &cy_capsense_tuner.sensorContext[0u].raw,
    &emptySlotValue,
    &cy_capsense_tuner.sensorContext[2u].raw,
    &emptySlotValue,
    &emptySlotValue,
    &cy_capsense_tuner.sensorContext[1u].raw,
    &emptySlotValue,
    &cy_capsense_tuner.sensorContext[3u].raw,
};
#endif

static const cy_stc_capsense_common_config_t cy_capsense_commonConfig =
{
    .cpuClkHz = CY_CAPSENSE_CPU_CLK,
    .periClkHz = CY_CAPSENSE_PERI_CLK,
    .vdda = CY_CAPSENSE_VDDA_MV,
    .numPin = CY_CAPSENSE_PIN_COUNT,
    .numSns = CY_CAPSENSE_SENSOR_COUNT,
    .numWd = CY_CAPSENSE_WIDGET_COUNT,
    .csdEn = CY_CAPSENSE_ENABLE,
    .csxEn = CY_CAPSENSE_DISABLE,
    .bistEn = CY_CAPSENSE_ENABLE,
    .positionFilterEn = CY_CAPSENSE_DISABLE,
    .periDividerType = (uint8_t)CY_CAPSENSE_PERI_DIV_TYPE,
    .periDividerIndex = CY_CAPSENSE_PERI_DIV_INDEX,
    .analogWakeupDelay = 10u,
    .proxTouchCoeff = 300u,
    .swSensorAutoResetEn = CY_CAPSENSE_DISABLE,
    .csdInactiveSnsConnection = CY_CAPSENSE_SNS_CONNECTION_GROUND,
    .csxInactiveSnsConnection = CY_CAPSENSE_SNS_CONNECTION_GROUND,
#if (CY_CAPSENSE_MW_VERSION >= 400)
    .isxInactiveSnsConnection = CY_CAPSENSE_SNS_CONNECTION_HIGHZ,
#endif
    .csdRConst = 1000u,
    .csdShieldNumPin = 0u,
    .csdRawTarget = 85u,
    .csdAutotuneEn = CY_CAPSENSE_CSD_SS_HW_EN,
    .csdCalibrationError = 10u,
    .csxRawTarget = 40u,
    .csxCalibrationError = 20u,
#if (CY_CAPSENSE_MW_VERSION >= 400)
    .isxRawTarget = 40u,
    .isxCalibrationError = 20u,
#endif
#if (CY_CAPSENSE_MW_VERSION >= 400)
    .ptrChConfig = &cy_capsense_msc_ch_config[0u],
#else
    .ptrMscChConfig = &cy_capsense_msc_ch_config[0u],
#endif
#if ((CY_CAPSENSE_DMA_CONFIGURED != 0) && (CY_CAPSENSE_SENSOR_CONNECTION_MODE_LEGACY == 0))
    .ptrDmacBase = DMAC,
    .ptrDmaWrChSnsCfgAddr = ptrDmaWrChSnsConfigs,
    .ptrDmaRdChSnsCfgAddr = ptrDmaRdChSnsConfigs,
#endif
    .csdShieldMode = CY_CAPSENSE_SHIELD_DISABLED,
    .sensorConnection = CY_CAPSENSE_CTRLMUX_SENSOR_CONNECTION_METHOD,
    .csdCdacAutocalEn = CY_CAPSENSE_ENABLE,
    .csdRefCdacAutoEn = CY_CAPSENSE_ENABLE,
    .csdCdacCompEn = CY_CAPSENSE_ENABLE,
    .csdCdacCompDivAutoEn = CY_CAPSENSE_ENABLE,
    .csdCdacAutoCalibMin = 6u,
    .csdRefCdacRowColumnAlignEn = CY_CAPSENSE_ENABLE,
    .csxCdacAutocalEn = CY_CAPSENSE_DISABLE,
    .csxRefCdacAutoEn = CY_CAPSENSE_DISABLE,
    .csxCdacCompEn = CY_CAPSENSE_DISABLE,
    .csxCdacCompDivAutoEn = CY_CAPSENSE_DISABLE,
    .csxCdacAutoCalibMin = 6u,
    .csxAutotuneEn = CY_CAPSENSE_CSD_SS_DIS,
#if (CY_CAPSENSE_MW_VERSION >= 400)
    .isxCdacAutocalEn = CY_CAPSENSE_DISABLE,
    .isxRefCdacAutoEn = CY_CAPSENSE_DISABLE,
    .isxCdacCompEn = CY_CAPSENSE_DISABLE,
    .isxCdacCompDivAutoEn = CY_CAPSENSE_DISABLE,
    .isxCdacAutoCalibMin = 6u,
    .isxAutotuneEn = CY_CAPSENSE_CSD_SS_DIS,
#endif
    .numProOffsetCycles = 0u,
    .proOffsetCdacComp = 0u,
    .scanningMode = CY_CAPSENSE_SCAN_MODE_INT_DRIVEN,
    .mptxEn = CY_CAPSENSE_DISABLE,
    .numEpiCycles = 120u,
    .chopPolarity = CY_CAPSENSE_DISABLE,
    .numCoarseInitChargeCycles = (CY_CAPSENSE_PERI_CLK / 1 / 240000),
    .numCoarseInitSettleCycles = (CY_CAPSENSE_PERI_CLK / 1 / 240000),
    .cicFilterMode = CY_CAPSENSE_CIC_FILTER,
    .numBadScans = 0u,
    .counterMode = CY_CAPSENSE_COUNTER_MODE_SATURATE,
    .syncFrameStartEn = CY_CAPSENSE_DISABLE,
    .syncClockEn = CY_CAPSENSE_DISABLE,
    .syncMode = CY_CAPSENSE_SYNC_INTERNAL,
    .masterChannelId = 0u,
    .numChips = 1u,
    .numChannels = CY_MSC_ENABLED_CH_NUMBER,
    .numSlots = CY_CAPSENSE_SLOT_COUNT,
    .channelOffset = CY_MSC_CHANNEL_OFFSET,
};

#if (CY_CAPSENSE_MULTI_PHASE_ENABLED)
    static cy_stc_capsense_mptx_table_t cy_capsense_mptx_table[CY_CAPSENSE_MPTX_WIDGET_NUMBER] =
    {
    };
#endif

static const cy_stc_capsense_pin_config_t cy_capsense_pinConfig[CY_CAPSENSE_PIN_COUNT] =
{
    { /* Button0_Sns0 */
        Button0_Sns0_PORT,
        Button0_Sns0_PIN,
        Button0_Sns0_PAD,
        0u,
    },
    { /* Button1_Sns0 */
        Button1_Sns0_PORT,
        Button1_Sns0_PIN,
        Button1_Sns0_PAD,
        1u,
    },
    { /* Button2_Sns0 */
        Button2_Sns0_PORT,
        Button2_Sns0_PIN,
        Button2_Sns0_PAD,
        0u,
    },
    { /* Button3_Sns0 */
        Button3_Sns0_PORT,
        Button3_Sns0_PIN,
        Button3_Sns0_PAD,
        1u,
    },
};

#if (CY_CAPSENSE_SHIELD_PIN_COUNT > 0)
    static const cy_stc_capsense_pin_config_t cy_capsense_shieldPinConfig[CY_CAPSENSE_SHIELD_PIN_COUNT] =
    {
    };
#endif

#if (CY_CAPSENSE_ELTD_COUNT > 0)
    static const cy_stc_capsense_electrode_config_t cy_capsense_electrodeConfig[CY_CAPSENSE_ELTD_COUNT] =
    {
        { /* Button0_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[0u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Button1_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[1u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
        { /* Button2_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[2u],
            .type = 0u,
            .numPins = 1u,
            .chId = 0u,
        },
        { /* Button3_Sns0 */
            .ptrPin = &cy_capsense_pinConfig[3u],
            .type = 0u,
            .numPins = 1u,
            .chId = 1u,
        },
    };
#endif

static const cy_stc_capsense_widget_config_t cy_capsense_widgetConfig[CY_CAPSENSE_WIDGET_COUNT] =
{
    { /* Button0 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[0u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[0u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[0u],
        .ptrEltdCapacitance = &cy_capsense_eltdCap[0u],
        .ptrSnsCapacitance = &cy_capsense_snsCap[0u],
        .ptrBslnInv = &cy_capsense_bslnInv[0u],
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[0u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 0u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
    { /* Button1 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[1u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[1u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[1u],
        .ptrEltdCapacitance = &cy_capsense_eltdCap[1u],
        .ptrSnsCapacitance = &cy_capsense_snsCap[1u],
        .ptrBslnInv = &cy_capsense_bslnInv[1u],
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[1u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 1u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
    { /* Button2 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[2u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[2u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[2u],
        .ptrEltdCapacitance = &cy_capsense_eltdCap[2u],
        .ptrSnsCapacitance = &cy_capsense_snsCap[2u],
        .ptrBslnInv = &cy_capsense_bslnInv[2u],
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[2u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 2u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
    { /* Button3 */
        .ptrWdContext = &cy_capsense_tuner.widgetContext[3u],
        .ptrSnsContext = &cy_capsense_tuner.sensorContext[3u],
        .ptrEltdConfig = &cy_capsense_electrodeConfig[3u],
        .ptrEltdCapacitance = &cy_capsense_eltdCap[3u],
        .ptrSnsCapacitance = &cy_capsense_snsCap[3u],
        .ptrBslnInv = &cy_capsense_bslnInv[3u],
        .ptrNoiseEnvelope = NULL,
        .ptrRawFilterHistory = NULL,
        .ptrRawFilterHistoryLow = NULL,
        .iirCoeff = 128u,
        .ptrDebounceArr = &cy_capsense_debounce[3u],
        .ptrDiplexTable = NULL,
        .centroidConfig = 0u,
        .xResolution = 0u,
        .yResolution = 0u,
        .numSns = 1u,
        .numCols = 1u,
        .numRows = 0u,
        .ptrPosFilterHistory = NULL,
        .ptrCsxTouchHistory = NULL,
        .ptrCsxTouchBuffer = NULL,
        .ptrCsdTouchBuffer = NULL,
        .ptrGestureConfig = NULL,
        .ptrGestureContext = NULL,
        .ballisticConfig = {
            .accelCoeff = 9u,
            .speedCoeff = 2u,
            .divisorValue = 4u,
            .speedThresholdX = 3u,
            .speedThresholdY = 4u,
        },
        .ptrBallisticContext = NULL,
        .aiirConfig = {
            .maxK = 60u,
            .minK = 1u,
            .noMovTh = 3u,
            .littleMovTh = 7u,
            .largeMovTh = 12u,
            .divVal = 64u,
        },
        .advConfig = {
            .penultimateTh = 100u,
            .virtualSnsTh = 100u,
            .crossCouplingTh = 5u,
        },
        .posFilterConfig = 0u,
        .rawFilterConfig = 0u,
        .senseMethod = CY_CAPSENSE_CSD_GROUP,
        .wdType = (uint8_t)CY_CAPSENSE_WD_BUTTON_E,
        .ptrMptxTable = NULL,
        .firstSlotId = 3u,
        .numSlots = 1u,
        .numChopCycles = 1u,
        .mptxOrder = 1u,
        .lfsrDitherLimit = 10u,
        .snsClkSourceAutoSelMode = CY_CAPSENSE_SNS_CLK_SOURCE_AUTO_SEL_MODE_STRONG,
        .mfsConfig = 0u,
    },
};

cy_stc_capsense_tuner_t cy_capsense_tuner =
{
    .commonContext = {
        #if (CY_CAPSENSE_MW_VERSION < 300)
            .configId = 0xc290,
        #elif (CY_CAPSENSE_MW_VERSION < 400)
            .configId = 0xc291,
        #else
            .configId = 0xc292,
        #endif

        .tunerCmd = 0u,
        .scanCounter = 0u,
        .tunerSt = 0u,
        .initDone = 0u,
        .status = 0u,
        .timestampInterval = 1u,
        .timestamp = 0u,
        .tunerCnt = 0u,
        .numFineInitCycles = 2u,
        .numFineInitWaitCycles = 120u,
        .lfsrPoly = 2124u,
        .lfsrScale = 0u,
        .cdacDitherSeed = 255u,
        .cdacDitherPoly = 142u,
        .modClk = 1u,
    },
    .widgetContext = {
        { /* Button0 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 100u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 16u,
            .rowSnsClk = 16u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 40u,
            .nNoiseTh = 40u,
            .hysteresis = 10u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 421u,
            .cdacRef = 41u,
            .rowCdacRef = 41u,
            .cicRate = 64u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 8u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
        { /* Button1 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 100u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 20u,
            .rowSnsClk = 20u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 40u,
            .nNoiseTh = 40u,
            .hysteresis = 10u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 416u,
            .cdacRef = 42u,
            .rowCdacRef = 42u,
            .cicRate = 64u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 10u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
        { /* Button2 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 100u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 20u,
            .rowSnsClk = 20u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 40u,
            .nNoiseTh = 40u,
            .hysteresis = 10u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 449u,
            .cdacRef = 45u,
            .rowCdacRef = 45u,
            .cicRate = 64u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 10u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
        { /* Button3 */
            .fingerCap = 160u,
            .sigPFC = 0u,
            .maxRawCount = 0u,
            #if (CY_CAPSENSE_MW_VERSION >= 300)
                .maxRawCountRow = 0u,
            #endif
            .fingerTh = 100u,
            .proxTh = 200u,
            .lowBslnRst = 30u,
            .snsClk = 28u,
            .rowSnsClk = 28u,
            .gestureDetected = 0u,
            .gestureDirection = 0u,
            .xDelta = 0,
            .yDelta = 0,
            .noiseTh = 40u,
            .nNoiseTh = 40u,
            .hysteresis = 10u,
            .onDebounce = 3u,
            .snsClkSource = CY_CAPSENSE_CLK_SOURCE_DIRECT,
            .bslnCoeff = 1u,
            .status = 0u,
            .wdTouch = {
                .ptrPosition = NULL,
                .numPosition = 0,
            },
            .numSubConversions = 419u,
            .cdacRef = 38u,
            .rowCdacRef = 38u,
            .cicRate = 64u,
            .cdacDitherEn = 1u,
            .cdacDitherValue = 0u,
            .coarseInitBypassEn = 0u,
            .cdacCompDivider = 14u,
            .lfsrBits = CY_CAPSENSE_LFSR_BITS_AUTO,
        },
    },
    .sensorContext = {
        { /* Button0_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 136u,
        },
        { /* Button1_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 179u,
        },
        { /* Button2_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 192u,
        },
        { /* Button3_Sns0 */
            .raw = 0u,
            .bsln = 0u,
            .diff = 0u,
            .status = 0u,
            .negBslnRstCnt = 0u,
            .bslnExt = 0u,
            .cdacComp = 226u,
        },
    },
};

#if (CY_CAPSENSE_BIST_EN != 0)
static cy_stc_capsense_bist_context_t cy_capsense_bist_context =
{
    .ptrWdgtCrc = &cy_capsense_wdgtCrc[0u],
    .snsIntgShortSettlingTime = 2u,
    .eltdCapModClk = 2u,
    .eltdCapSnsClk = 0u,
    .eltdCapNumCoarseInitChargeCycles = 200u,
    .eltdCapNumCoarseInitSettleCycles = 200u,
    .eltdCapNumFineInitCycles = 10u,
    .shieldCapISC = CY_CAPSENSE_BIST_IO_STRONG_E,
    .eltdCapCsdISC = CY_CAPSENSE_BIST_IO_STRONG_E,
    .eltdCapCsxISC = CY_CAPSENSE_BIST_IO_STRONG_E,
    .ptrChShieldCap = &cy_capsense_shieldCap[0u],
};
#endif

cy_stc_capsense_context_t cy_capsense_context =
{
    .ptrCommonConfig = &cy_capsense_commonConfig,
    .ptrCommonContext = &cy_capsense_tuner.commonContext,
    .ptrInternalContext = &cy_capsense_internalContext,
    .ptrWdConfig = &cy_capsense_widgetConfig[0u],
    .ptrWdContext = &cy_capsense_tuner.widgetContext[0u],
    .ptrPinConfig = &cy_capsense_pinConfig[0u],
    .ptrShieldPinConfig = NULL,
    .ptrActiveScanSns = &cy_capsense_activeScanSns[0u],
    .ptrBistContext = &cy_capsense_bist_context,
    .ptrBaseFrameContext = &cy_capsense_baseFrame[0],
    .ptrSensorFrameContext = &cy_capsense_sensorFrameContext[0],
    .ptrScanSlots = &cy_capsense_scanSlotsConfig[0],
};

#endif /* CY_CAPSENSE_CORE == __CORTEX_M */

#endif /* !defined(CY_DISABLE_CAPSENSE) */

#endif /* (defined(COMPONENT_MW_CAPSENSE) || !defined(COMPONENT_MW_CORE_MAKE)) */

/* [] END OF FILE */
