#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
bsp-assistant:
	(cd Everyday-Work-Safety; make bsp-assistant)
.PHONY: bsp-assistant

config_bt:
	(cd Everyday-Work-Safety; make config_bt)
.PHONY: config_bt

bt-configurator:
	(cd Everyday-Work-Safety; make bt-configurator)
.PHONY: bt-configurator

capsense-configurator:
	(cd Everyday-Work-Safety; make capsense-configurator)
.PHONY: capsense-configurator

capsense-tuner:
	(cd Everyday-Work-Safety; make capsense-tuner)
.PHONY: capsense-tuner

config:
	(cd Everyday-Work-Safety; make config)
.PHONY: config

device-configurator:
	(cd Everyday-Work-Safety; make device-configurator)
.PHONY: device-configurator

config_ezpd:
	(cd Everyday-Work-Safety; make config_ezpd)
.PHONY: config_ezpd

ez-pd-configurator:
	(cd Everyday-Work-Safety; make ez-pd-configurator)
.PHONY: ez-pd-configurator

modlibs:
	(cd Everyday-Work-Safety; make modlibs)
.PHONY: modlibs

library-manager:
	(cd Everyday-Work-Safety; make library-manager)
.PHONY: library-manager

config_lin:
	(cd Everyday-Work-Safety; make config_lin)
.PHONY: config_lin

lin-configurator:
	(cd Everyday-Work-Safety; make lin-configurator)
.PHONY: lin-configurator

qspi-configurator:
	(cd Everyday-Work-Safety; make qspi-configurator)
.PHONY: qspi-configurator

seglcd-configurator:
	(cd Everyday-Work-Safety; make seglcd-configurator)
.PHONY: seglcd-configurator

smartio-configurator:
	(cd Everyday-Work-Safety; make smartio-configurator)
.PHONY: smartio-configurator

config_usbdev:
	(cd Everyday-Work-Safety; make config_usbdev)
.PHONY: config_usbdev

usbdev-configurator:
	(cd Everyday-Work-Safety; make usbdev-configurator)
.PHONY: usbdev-configurator

